// Mock data for products
export const mockProducts = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    price: 149.99,
    image: "/sections/wireless-headphones.jpg",
    rating: 4.5,
    reviewCount: 1245,
    category: "electronics",
    isPrime: true,
    discount: 20,
    slug: "wireless-bluetooth-headphones",
    currency: "USD",
  },
  {
    id: "2",
    name: "Smartphone 128GB Unlocked",
    price: 699.99,
    image: "/sections/smartphone.jpg",
    rating: 4.7,
    reviewCount: 3456,
    category: "electronics",
    isPrime: true,
    slug: "smartphone-128gb-unlocked",
    currency: "USD",
  },
  {
    id: "3",
    name: "Men's Casual Cotton T-Shirt",
    price: 19.99,
    image: "/sections/t-shirt.jpg",
    rating: 4.2,
    reviewCount: 876,
    category: "clothing",
    discount: 15,
    slug: "mens-casual-cotton-t-shirt",
    currency: "USD",
  },
  {
    id: "4",
    name: "Women's Running Shoes",
    price: 89.99,
    image: "/sections/running-shoes.jpg",
    rating: 4.6,
    reviewCount: 1023,
    category: "clothing",
    isPrime: true,
    slug: "womens-running-shoes",
    currency: "USD",
  },
  {
    id: "5",
    name: "Smart Home Security Camera",
    price: 79.99,
    image: "/sections/security-camera.jpg",
    rating: 4.3,
    reviewCount: 567,
    category: "electronics",
    isPrime: true,
    discount: 10,
    slug: "smart-home-security-camera",
    currency: "USD",
  },
  {
    id: "6",
    name: "Non-Stick Cooking Pan Set",
    price: 49.99,
    image: "/sections/pan-set.jpg",
    rating: 4.4,
    reviewCount: 789,
    category: "home",
    slug: "non-stick-cooking-pan-set",
    currency: "USD",
  },
  {
    id: "7",
    name: "Portable Bluetooth Speaker",
    price: 39.99,
    image: "/sections/speaker.jpg",
    rating: 4.1,
    reviewCount: 432,
    category: "electronics",
    discount: 25,
    slug: "portable-bluetooth-speaker",
    currency: "USD",
  },
  {
    id: "8",
    name: "Stainless Steel Water Bottle",
    price: 24.99,
    image: "/sections/water-bottle.jpg",
    rating: 4.8,
    reviewCount: 1567,
    category: "home",
    isPrime: true,
    slug: "stainless-steel-water-bottle",
    currency: "USD",
  },
  {
    id: "9",
    name: "Wireless Charging Pad",
    price: 29.99,
    image: "/sections/charging-pad.jpg",
    rating: 4.0,
    reviewCount: 345,
    category: "electronics",
    slug: "wireless-charging-pad",
    currency: "USD",
  },
  {
    id: "10",
    name: "Yoga Mat with Carrying Strap",
    price: 34.99,
    image: "/sections/yoga-mat.jpg",
    rating: 4.5,
    reviewCount: 678,
    category: "sports",
    discount: 15,
    slug: "yoga-mat-with-carrying-strap",
    currency: "USD",
  },
  {
    id: "11",
    name: "Digital Kitchen Scale",
    price: 19.99,
    image: "/sections/kitchen-scale.jpg",
    rating: 4.6,
    reviewCount: 890,
    category: "home",
    isPrime: true,
    slug: "digital-kitchen-scale",
    currency: "USD",
  },
  {
    id: "12",
    name: "Adjustable Dumbbell Set",
    price: 199.99,
    image: "/sections/dumbbell-set.jpg",
    rating: 4.7,
    reviewCount: 456,
    category: "sports",
    isPrime: true,
    discount: 10,
    slug: "adjustable-dumbbell-set",
    currency: "USD",
  },
]

// Mock data for categories
export const mockCategories = [
  {
    id: "1",
    name: "Electronics",
    image: "/sections/electronics.jpg",
    slug: "electronics",
  },
  {
    id: "2",
    name: "Clothing",
    image: "/sections/clothing.jpg",
    slug: "clothing",
  },
  {
    id: "3",
    name: "Books",
    image: "/sections/books.jpg",
    slug: "books",
  },
  {
    id: "4",
    name: "Home & Kitchen",
    image: "/sections/home-kitchen.jpg",
    slug: "home",
  },
  {
    id: "5",
    name: "Toys & Games",
    image: "/sections/toys.jpg",
    slug: "toys",
  },
  {
    id: "6",
    name: "Sports & Outdoors",
    image: "/sections/outdoor-sports.jpg",
    slug: "sports",
  },
  {
    id: "7",
    name: "Beauty & Personal Care",
    image: "/sections/beauty.jpg",
    slug: "beauty",
  },
  {
    id: "8",
    name: "Grocery",
    image: "/sections/grocery.jpg",
    slug: "grocery",
  },
]

// Mock data for deals
export const mockDeals = [
  {
    id: "1",
    name: "Wireless Earbuds with Charging Case",
    regularPrice: 79.99,
    salePrice: 39.99,
    discount: 50,
    image: "/sections/wireless-earbuds.jpg",
    timeRemaining: 12 * 60 * 60 * 1000, // 12 hours in milliseconds
    slug: "wireless-earbuds",
  },
  {
    id: "2",
    name: "Robot Vacuum Cleaner",
    regularPrice: 299.99,
    salePrice: 199.99,
    discount: 33,
    image: "/sections/robot-vacuum-cleaner.jpg",
    timeRemaining: 8 * 60 * 60 * 1000, // 8 hours in milliseconds
    slug: "robot-vacuum-cleaner",
  },
  {
    id: "3",
    name: "Electric Pressure Cooker",
    regularPrice: 129.99,
    salePrice: 89.99,
    discount: 30,
    image: "/sections/pressure-cooker.jpg",
    timeRemaining: 16 * 60 * 60 * 1000, // 16 hours in milliseconds
    slug: "electric-pressure-cooker",
  },
  {
    id: "4",
    name: "Fitness Tracker with Heart Rate Monitor",
    regularPrice: 99.99,
    salePrice: 59.99,
    discount: 40,
    image: "/sections/fitness-tracker.jpg",
    timeRemaining: 24 * 60 * 60 * 1000, // 24 hours in milliseconds
    slug: "fitness-tracker",
  },
  {
    id: "5",
    name: "Portable Power Bank 20000mAh",
    regularPrice: 49.99,
    salePrice: 29.99,
    discount: 40,
    image: "/sections/power-bank.jpg",
    timeRemaining: 36 * 60 * 60 * 1000, // 36 hours in milliseconds
    slug: "portable-power-bank",
  },
  {
    id: "6",
    name: "Smart LED TV 55-inch",
    regularPrice: 599.99,
    salePrice: 399.99,
    discount: 33,
    image: "/sections/smart-tv.jpg",
    timeRemaining: 48 * 60 * 60 * 1000, // 48 hours in milliseconds
    slug: "smart-led-tv",
  },
]
