export enum InventoryStatus {
  IN_STOCK = "IN_STOCK",
  OUT_OF_STOCK = "OUT_OF_STOCK",
  LOW_STOCK = "LOW_STOCK",
  BACKORDER = "BACKORDER",
  PRE_ORDER = "PRE_ORDER",
  DISCONTINUED = "DISCONTINUED",
  ON_HOLD = "ON_HOLD",
  DAMAGED = "DAMAGED",
  IN_TRANSIT = "IN_TRANSIT",
  RETURNED = "RETURNED",
}
