export enum ProductVariationType {
  COLOR = "COLOR",
  SIZE = "SIZE",
  MATERIAL = "MATERIAL",
  STYLE = "STYLE",
  PATTERN = "PATTERN",
  FLAVOR = "FLAVOR",
  PACKAGE = "PACKAGE",
  VOLUME = "VOLUME",
  WEIGHT = "WEIGHT",
  COUNT = "COUNT",
  OTHER = "OTHER",
}

export enum ProductStatus {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  ARCHIVED = "ARCHIVED",
  OUT_OF_STOCK = "OUT_OF_STOCK",
  DISCONTINUED = "DISCONTINUED",
  PENDING_REVIEW = "PENDING_REVIEW",
  REJECTED = "REJECTED",
}

export enum ProductCondition {
  NEW = "NEW",
  REFURBISHED = "REFURBISHED",
  USED_LIKE_NEW = "USED_LIKE_NEW",
  USED_GOOD = "USED_GOOD",
  USED_FAIR = "  USED_FAIR",
  USED_POOR = "USED_POOR",
  COLLECTIBLE_LIKE_NEW = "COLLECTIBLE_LIKE_NEW",
  COLLECTIBLE_VERY_GOOD = "COLLECTIBLE_VERY_GOOD",
  COLLECTIBLE_GOOD = "COLLECTIBLE_GOOD",
}
