export enum SellerStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  SUSPENDED = "SUSPENDED",
  REJECTED = "REJECTED",
}

export enum BusinessType {
  INDIVIDUAL = "INDIVIDUAL",
  PRIVATE_COMPANY = "PRIVATE_COMPANY",
  PUBLIC_COMPANY = "PUBLIC_COMPANY",
  NON_PROFIT = "NON_PROFIT",
}
